### ISSUE TITLE
Failed to load the atom-development-server package

### ISSUE THREAD

**Issue by xvaara** [joaoafrmartins/development-server#11]
Installed directly to ~/.atom/packages from git.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-development-server](https://github.com/joaoafrmartins/development-server) package, v0.4.2
### Stack Trace

Failed to load the atom-development-server package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/xdanger/tmp/development-server/lib/views/notify/note.coffee:1:1)
    at /Users/xdanger/tmp/development-server/lib/views/notify/note.coffee:7:3
    at Object.<anonymous> (/Users/xdanger/tmp/development-server/lib/views/notify/note.coffee:7:3)
    at Object.<anonymous> (/Users/xdanger/tmp/development-server/lib/views/notify/note.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xdanger/tmp/development-server/lib/views/notify/index.coffee:3:8)
    at Object.<anonymous> (/Users/xdanger/tmp/development-server/lib/views/notify/index.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xdanger/tmp/development-server/lib/views/index.coffee:5:15)
    at Object.<anonymous> (/Users/xdanger/tmp/development-server/lib/views/index.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xdanger/tmp/development-server/lib/development-server.coffee:1:9)
    at Object.<anonymous> (/Users/xdanger/tmp/development-server/lib/development-server.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:386:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:667:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:38:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:49:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:79:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "jsformat"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-autocomplete-openresty, v0.0.1
emmet, v2.3.15
emmet-simplified, v2.5.0
highlight-selected, v0.11.1
language-lua, v0.9.4
language-moonscript, v1.7.0
language-perl-template-toolkit, v0.1.0
linter, v1.11.2
linter-lua, v1.0.0
linter-perl, v0.7.0
minimap, v4.16.2
nucleus-dark-ui, v0.6.12
perltidy, v2.2.0
powerline, v0.1.0
rest-client, v0.5.0

# Dev
No dev packages
```

**Comment by chensivan** [comment]
Same here.
